const config = {
  encoding: "utf-8",
  max_number: 10,
  showMessage: true,
  auto_sort: true,
  timeFormat: "%Y",
  color: {},
  color_range: ["#1177CC", "#113388"],
  itemLabel: "",
  typeLabel: "1960-2017",
  item_x: 3000,
  interval_time: 1,
  text_y: -50,
  text_x: 950,
  offset: 300,
  display_barInfo: 300,
  step: 7,
  format: ",.0f",
  postfix: "",
  deformat: function (val, postfix) {
    return Number(val.replace(postfix, "").replace(/\,/g, ""));
  },
  left_margin: 235,
  right_margin: 150,
  top_margin: 180,
  bottom_margin: 0,
  dateLabel_switch: "visible",
  dateLabel_x: 1550,
  dateLabel_y: 530,
  wait: 2,
  update_rate: 1,
  showLabel: true,
  labelx: -10,
  background_color: "#FFF",
  show_x_tick: true,
  bar_name_max: 30,
};
